openapi: 3.0.0
info:
  title: Vorpal Authentication API
  version: '1.0'
  x-logo:
    url: https://vorpal.gg/public/templates/assets/images/logo.png
  description: >
    Welcome to the developer portal for our API, everything you need to interact with our API is here. Alternatively you may check out our github for premade API libraries for a variety of programming languages.

    ## Frequently asked questions
    
    ### What's up with all parameters?
    
    All parameters are encoded in base64, use this website to do so https://www.base64encode.org/

    ### Where is my ValorId?
    
    You may find your ValorId (also known as Brand Key), in your Brand Settings page by clicking "Edit Brand" on your desired brand.
    
    ### How do i get my ValorKey?
    
    The ValorKey must be generated live just before you send in the request, here is a c++ example.
  

# Servers section defines the base URL for API endpoints.
servers:
- url: http://vorpal.gg/API/
  description: Main (production) server

# Paths section contains the individual API endpoints with their methods and details.
paths:

  # /register endpoint for user registration.
  /register:
    post:
      summary: Register a new user
      operationId: Register_POST

      # Request parameters in the header.
      parameters:
      - name: Content-Type
        in: header
        description: The content type of the request body.
        required: true
        style: simple
        schema:
          enum:
          - application/x-www-form-urlencoded
        type: string
        example: application/x-www-form-urlencoded

      - name: User-Agent
        in: header
        description: The user agent making the request. This is always Vorpal Client 1.0.
        required: true
        style: simple
        schema:
          type: string
        example: Vorpal Client 1.0

      - name: ValorId
        in: header
        description: The Valor ID of the API consumer.
        required: true
        style: simple
        schema:
          type: string
        example: YXV0aF92b3JwYWxfNjQ5MDkxMWU4NGVlZA

      - name: ValorKey
        in: header
        description: Also known as brand key, found in brand settings.
        required: true
        style: simple
        schema:
          type: string
        example: D398B29D3DBBB9BF201D4C7E1C19FF9D43C15FD45A0CEC46FBE9885EC3F6E97F

      # Request body contains user registration information.
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - email
              - password
              - username
              type: object
              properties:
                email:
                  type: string
                  example: dGVzdEB2b3JwYWwuZ2c
                password:
                  type: string
                  example: dGVzdDEyMzQ1Ng
                username:
                  type: string
                  example: dGVzdDEyMzQ1
        required: false

      # Response for a successful registration.
      responses:
        '200':
          description: Successful registration
          headers:
            Authorization:
              content:
                text/plain:
                  schema:
                    type: string
                  example: e421d2b4568df6a447faeac17957c5f7f59599bf14e751fdbee19dd9df87825a
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
                example:
                  Result: true
                  Time: 1690096285
              example:
                Result: true
                Time: 1690096285
        '433':
          description: Vorpal error response
          headers:
            Authorization:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 532420495d16a460fdb4fd6067be02a9b706c9adafc59e10ac607fb508bf647c
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
                example:
                  Result: false
                  Time: 1690096293
                  Error: Invalid Info
              example:
                Result: false
                Time: 1690096293
                Error: Invalid Info
      deprecated: false
      security: []

  # /brandvariables endpoint for handling brand variables.
  /brandvariables:
    post:
      summary: Fetch brand variables
      operationId: Brandvariables_POST

      # Request parameters in the header.
      parameters:
      - name: Content-Type
        in: header
        description: The content type of the request body.
        required: true
        style: simple
        schema:
          enum:
          - application/x-www-form-urlencoded
        type: string
        example: application/x-www-form-urlencoded

      - name: User-Agent
        in: header
        description: The user agent making the request. This is always Vorpal Client 1.0.
        required: true
        style: simple
        schema:
          type: string
        example: Vorpal Client 1.0

      - name: ValorId
        in: header
        description: The Valor ID of the API consumer.
        required: true
        style: simple
        schema:
          type: string
        example: YXV0aF92b3JwYWxfNjQ5MDkxMWU4NGVlZA

      - name: ValorKey
        in: header
        description: Also known as brand key, found in brand settings.
        required: true
        style: simple
        schema:
          type: string
        example: D398B29D3DBBB9BF201D4C7E1C19FF9D43C15FD45A0CEC46FBE9885EC3F6E97F

      responses:
        '200':
          description: Successful brand variables request
          headers:
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
                example:
                  Brand-Key: value
              example:
                Brand-Key: value
        '433':
          description: Vorpal error response
          headers:
            Authorization:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 532420495d16a460fdb4fd6067be02a9b706c9adafc59e10ac607fb508bf647c
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
                example:
                  Result: false
                  Time: 1690096293
                  Error: Invalid Info
              example:
                Result: false
                Time: 1690096293
                Error: Invalid Info
      deprecated: false
      security: []

  # /login endpoint for user login.
  /login:
    post:
      summary: User login
      operationId: Login_POST

      # Request parameters in the header.
      parameters:
      - name: Content-Type
        in: header
        description: The content type of the request body.
        required: true
        style: simple
        schema:
          enum:
          - application/x-www-form-urlencoded
        type: string
        example: application/x-www-form-urlencoded

      - name: User-Agent
        in: header
        description: The user agent making the request. This is always Vorpal Client 1.0.
        required: true
        style: simple
        schema:
          type: string
        example: Vorpal Client 1.0

      - name: ValorId
        in: header
        description: The Valor ID of the API consumer.
        required: true
        style: simple
        schema:
          type: string
        example: YXV0aF92b3JwYWxfNjQ5MDkxMWU4NGVlZA

      - name: ValorKey
        in: header
        description: Also known as brand key, found in brand settings.
        required: true
        style: simple
        schema:
          type: string
        example: D398B29D3DBBB9BF201D4C7E1C19FF9D43C15FD45A0CEC46FBE9885EC3F6E97F

      # Request body contains user login information.
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - hwid
              - password
              - username
              type: object
              properties:
                hwid:
                  type: string
                  example: MTZkNmM5ZGYwMzI1OWU3MmFmM2I2NGU5MGU1NTIwNDJjNjI2ZDY1YzFlNzkyNDliZWY1MTljZjRjNDUwZGY4OA
                password:
                  type: string
                  example: dGVzdDEyMzQ1Ng
                username:
                  type: string
                  example: dGVzdDEyMzQ1
        required: false

      # Response for a successful login.
      responses:
        '200':
          description: Successful login
          headers:
            Authorization:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 442acbffba5c68f468b6d067d9bd36edea39a43bafb8b134990174dc834d2af3
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
                example:
                  HashedID: NUNZNUIzbW5JT01mZC9mWGliaWdOUT09
                  Username: test12345
                  Email: test@vorpal.gg
                  Status: '1'
                  Rank: '0'
                  KeyInfo:
                    aFJpUG5sOHFBb21ySk5OazlWSUsyZz09:
                    - licenseKey: vorpal-testlicense
                      expiryDays: '30'
                      expiryDate: 1692688289
                      hwid: ''
                      status: 1
                      lastHWIDReset: 0
                      ApplicationName: Application
                  Time: 1690260886
                  Result: true
              example:
                HashedID: NUNZNUIzbW5JT01mZC9mWGliaWdOUT09
                Username: test12345
                Email: test@vorpal.gg
                Status: '1'
                Rank: '0'
                KeyInfo:
                  aFJpUG5sOHFBb21ySk5OazlWSUsyZz09:
                  - licenseKey: vorpal-testlicense
                    expiryDays: '30'
                    expiryDate: 1692688289
                    hwid: ''
                    status: 1
                    lastHWIDReset: 0
                    ApplicationName: Application
                Time: 1690260886
                Result: true
        '433':
          description: Vorpal error response
          headers:
            Authorization:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 532420495d16a460fdb4fd6067be02a9b706c9adafc59e10ac607fb508bf647c
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
                example:
                  Result: false
                  Time: 1690096293
                  Error: Invalid Info
              example:
                Result: false
                Time: 1690096293
                Error: Invalid Info
      deprecated: false
      security: []

  # /redeemLicense endpoint for redeeming a license.
  /redeemLicense:
    post:
      summary: Redeem a license
      operationId: RedeemLicense_POST

      # Request parameters in the header.
      parameters:
      - name: Content-Type
        in: header
        description: The content type of the request body.
        required: true
        style: simple
        schema:
          enum:
          - application/x-www-form-urlencoded
        type: string
        example: application/x-www-form-urlencoded

      - name: User-Agent
        in: header
        description: The user agent making the request. This is always Vorpal Client 1.0.
        required: true
        style: simple
        schema:
          type: string
        example: Vorpal Client 1.0

      - name: ValorId
        in: header
        description: The Valor ID of the API consumer.
        required: true
        style: simple
        schema:
          type: string
        example: YXV0aF92b3JwYWxfNjQ5MDkxMWU4NGVlZA

      - name: ValorKey
        in: header
        description: Also known as brand key, found in brand settings.
        required: true
        style: simple
        schema:
          type: string
        example: D398B29D3DBBB9BF201D4C7E1C19FF9D43C15FD45A0CEC46FBE9885EC3F6E97F

      # Request body contains license key and username.
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - licensekey
              - username
              type: object
              properties:
                licensekey:
                  type: string
                  example: dm9ycGFsLVRFU1RMSUNFTlNF
                username:
                  type: string
                  example: dGVzdDEyMzQ1
        required: false

      # Response for a successful license redemption.
      responses:
        '200':
          description: Successful license redemption
          headers:
            Authorization:
              content:
                text/plain:
                  schema:
                    type: string
                  example: a823c28a53f67ad060ccf340c14920d23868d75045b98bf4575850094e110d6c
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
                example:
                  Result: true
                  Time: 1690096289
                  Info: Successfully redeemed the product Application for 30 days
              example:
                Result: true
                Time: 1690096289
                Info: Successfully redeemed the product Application for 30 days
        '433':
          description: Vorpal error response
          headers:
            Authorization:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 532420495d16a460fdb4fd6067be02a9b706c9adafc59e10ac607fb508bf647c
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
                example:
                  Result: false
                  Time: 1690096293
                  Error: Invalid Info
              example:
                Result: false
                Time: 1690096293
                Error: Invalid Info
      deprecated: false
      security: []

  # /checkApplication endpoint for checking an application.
  /checkApplication:
    post:
      summary: Fetch application data
      operationId: CheckApplication_POST

      # Request parameters in the header.
      parameters:
      - name: Content-Type
        in: header
        description: The content type of the request body.
        required: true
        style: simple
        schema:
          enum:
          - application/x-www-form-urlencoded
        type: string
        example: application/x-www-form-urlencoded

      - name: User-Agent
        in: header
        description: The user agent making the request. This is always Vorpal Client 1.0.
        required: true
        style: simple
        schema:
          type: string
        example: Vorpal Client 1.0

      - name: ValorId
        in: header
        description: The Valor ID of the API consumer.
        required: true
        style: simple
        schema:
          type: string
        example: YXBwaWQ

      - name: ValorKey
        in: header
        description: Also known as brand key, found in brand settings.
        required: true
        style: simple
        schema:
          type: string
        example: D398B29D3DBBB9BF201D4C7E1C19FF9D43C15FD45A0CEC46FBE9885EC3F6E97F

      # Response for checking an application.
      responses:
        '200':
          description: Application data successfully fetched
          headers:
            Authorization:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 79c8179009116fa4ecf05dc1a582b08abf673501bfe6359fd590c885da8c14fa
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
                example:
                  Name: Application
                  Domain: sub.test.com
                  Version: '1'
                  Key: '18'
                  HWID: true
                  Maintenance: false
                  Developer: false
                  AntiDebug: false
                  AntiVM: false
                  Time: 1690260888
                  Result: true
              example:
                Name: Application
                Domain: sub.test.com
                Version: '1'
                Key: '18'
                HWID: true
                Maintenance: false
                Developer: false
                AntiDebug: false
                AntiVM: false
                Time: 1690260888
                Result: true
        '433':
          description: Vorpal error response
          headers:
            Authorization:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 532420495d16a460fdb4fd6067be02a9b706c9adafc59e10ac607fb508bf647c
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
                example:
                  Result: false
                  Time: 1690096293
                  Error: Invalid Info
              example:
                Result: false
                Time: 1690096293
                Error: Invalid Info
      deprecated: false
      security: []

  # /variable endpoint for handling variables.
  /variable:
    post:
      summary: Fetch variable
      operationId: Variable_POST

      # Request parameters in the header.
      parameters:
      - name: Content-Type
        in: header
        description: The content type of the request body.
        required: true
        style: simple
        schema:
          enum:
          - application/x-www-form-urlencoded
        type: string
        example: application/x-www-form-urlencoded

      - name: User-Agent
        in: header
        description: The user agent making the request. This is always Vorpal Client 1.0.
        required: true
        style: simple
        schema:
          type: string
        example: Vorpal Client 1.0

      - name: ValorId
        in: header
        description: The Valor ID of the API consumer.
        required: true
        style: simple
        schema:
          type: string
        example: YXBwaWQ

      - name: ValorKey
        in: header
        description: Also known as brand key, found in brand settings.
        required: true
        style: simple
        schema:
          type: string
        example: D398B29D3DBBB9BF201D4C7E1C19FF9D43C15FD45A0CEC46FBE9885EC3F6E97F

      - name: VariableKey
        in: header
        description: The key for the variable.
        required: true
        style: simple
        schema:
          type: string
        example: S2V5

      # Response for posting variables.
      responses:
        '200':
          description: Variable successfully fetched
          headers:
            Authorization:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 6a5fa24af58edd754a85850c1e3b4a409e5aee19af4f265741e8112a1efca92c
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
                example:
                  Key: Value
                  Result: true
                  Time: 1690260891
              example:
                Key: Value
                Result: true
                Time: 1690260891
        '433':
          description: Vorpal error response
          headers:
            Authorization:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 532420495d16a460fdb4fd6067be02a9b706c9adafc59e10ac607fb508bf647c
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
                example:
                  Result: false
                  Time: 1690096293
                  Error: Invalid Info
              example:
                Result: false
                Time: 1690096293
                Error: Invalid Info
      deprecated: false
      security: []

# Components section contains reusable schemas and components.
components:
  schemas:
    ErrorResponse:
      title: ErrorResponse
      description: Error response object for API calls.
      required:
      - Result
      - Time
      - Error
      type: object
      properties:
        Result:
          type: boolean
          description: Flag indicating whether the operation was successful.
        Time:
          type: integer
          format: int32
          description: The timestamp of the error occurrence.
        Error:
          type: string
          description: A description of the error.
      example:
        Result: false
        Time: 1690096291
        Error: Invalid Info
tags: []